spring:
  sql:
    init:
      mode: always
  application:
    name: wagle-server
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:13306/wagle?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 16379

jwt:
  token:
    secret-key: ${JWT_SECRET_KEY:waglewagle-secret-key-must-be-very-long-and-secure-enough}
    expiration:
      access: 604800000

cors:
  allowed-origins: http://localhost:3000,https://wagle-client.vercel.app,http://172.30.1.73:3000

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
      probes:
        enabled: true

